services:
    app.form.type.user.authentication.authenticate:
        class: AppBundle\Form\Type\User\AuthenticateUserType
        public: true
        arguments: ['@router']
        tags:
        - { name: form.type, alias: app_form_type_user_authentication_authenticate }