services:
  app.listener.affiliation:
    class: AppBundle\Service\Listener\PostListener
    tags:
    - { name: doctrine.orm.entity_listener, entity: AppBundle\Entity\Post, event: prePersist }
    - { name: doctrine.orm.entity_listener, entity: AppBundle\Entity\Post, event: preUpdate }