services:
    app.util.abstract_container_aware:
        abstract: true
        calls:
        - [setContainer, ['@service_container']]

    app.util.token_generator:
        class: AppBundle\Service\Util\TokenGenerator

    app.util.console:
        class: AppBundle\Service\Util\Console\Console
        parent: app.util.abstract_container_aware
        calls:
            - [setSession, ['@session']]
        public: true

    pdo:
        class: PDO
        arguments:
            - 'mysql:host=%database_host%;dbname=%database_name%'
            - '%database_user%'
            - '%database_password%'
        calls:
        - [ setAttribute, [3, 2] ] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION

    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments:
        - !service { class: PDO, factory: 'database_connection:getWrappedConnection' }
        - {lock_mode: 0}