<?php

namespace AppBundle\Repository;

/**
 * AchievementModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AchievementModelRepository extends \Doctrine\ORM\EntityRepository
{
}
