<?php

namespace AppBundle\Repository;

/**
 * AvatarModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvatarModelRepository extends \Doctrine\ORM\EntityRepository
{
}
