<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Post;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMostLatestPublished()
    {
        return $this->_em->createQueryBuilder()
            ->select('post')
            ->from(Post::class, 'post')
            ->where('post.published = 1')
            ->orderBy('post.lastUpdate', 'DESC')
            ->getQuery()->getResult();
    }

    public function findMostLikedPublished()
    {
        return $this->_em->createQueryBuilder()
            ->select('post')
            ->from(Post::class, 'post')
            ->where('post.published = 1')
            ->orderBy('post.numberOfLikes', 'DESC')
            ->getQuery()->getResult();
    }

    public function findMostFavoritePublished()
    {
        return $this->_em->createQueryBuilder()
            ->select('post')
            ->from(Post::class, 'post')
            ->where('post.published = 1')
            ->orderBy('post.numberOfFavorites', 'DESC')
            ->getQuery()->getResult();
    }

    public function findMostRisingPublished()
    {
        return $this->_em->createQueryBuilder()
            ->select('post')
            ->from(Post::class, 'post')
            ->where('post.published = 1')
            ->orderBy('post.numberOfLikes', 'DESC')
            ->getQuery()->getResult();
    }
}
