imports:
- { resource: parameters.yml }
- { resource: security.yml }
- { resource: services.yml }
- { resource: settings.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    templating:
        engines: ['twig']
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.pdo
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        "%kernel.project_dir%/src/AppBundle/Resources/views/Layout": Layout
        "%kernel.project_dir%/src/AppBundle/Resources/views/Mail": Mail
        "%kernel.project_dir%/src/AppBundle/Resources/views/Page": Page
    globals:
        request_business: '@app.business.request'
        user_business: '@app.business.user'
        vote_business: '@app.business.vote'
        achievement_business: '@app.business.achievement'
        post_bussiness: '@app.business.post'
        util_console: '@app.util.console'
        mailer_parameters: '%mailer_params%'
    form_themes:
        - '@Layout/Form/default.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    port: '%mailer_port%'
    auth_mode: '%mailer_auth_mode%'
    spool: { type: memory }

sensio_framework_extra:
    router:
        annotations: false

vich_uploader:
    db_driver: orm
    mappings:
        file:
            uri_prefix: /uploads/file
            upload_destination: '%upload.file.directory%'
            namer: vich_uploader.namer_uniqid

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

# Web Socket Configuration
gos_web_socket:
    server:
        host: '%server_ip%' #The host ip to bind to
        port: 8080        #The port the socket server will listen on
        router:
            resources:
            - '@AppBundle/Resources/config/routing/topic/all.yml'
    pushers:
        zmq:
            host: '%server_ip%'
            port: 5555
            persistent: true
            protocol: tcp
    client:
        firewall: main
        session_handler: '@session.handler.pdo'
        storage:
            driver: '@gos_web_socket.client_storage.driver.redis'
            decorator: '@gos_web_socket.client_storage.doctrine.decorator'

doctrine_cache:
    providers:
        redis_cache:
            redis:
                host: '%server_ip%'
                port: 6379
                database: 3
        websocket_cache_client:
            type: redis
            alias: gos_web_socket.client_storage.driver.redis