app_achievement:
    resource: "achievement/all.yml"
    prefix:   /achievement/

app_admin:
    resource: "admin/all.yml"
    prefix:   /admin/

app_comment:
    resource: "comment/all.yml"
    prefix:   /comment/

app_information:
    resource: "information/all.yml"
    prefix:   /information/

app_post:
    resource: "post/all.yml"
    prefix:   /post/

app_uploaded:
    resource: "uploaded/all.yml"
    prefix:   /uploaded/

app_user:
    resource: "user/all.yml"
    prefix:   /user/

app_home:
    resource: "home.yml"
    prefix:   /