app_admin_achievement:
    resource: "achievement/all.yml"
    prefix:   /achievement/

app_admin_achievement_model:
    resource: "achievement_model/all.yml"
    prefix:   /achievement_model/

app_admin_avatar_model:
    resource: "avatar_model/all.yml"
    prefix:   /avatar_model/

app_admin_post:
    resource: "post/all.yml"
    prefix:   /post/

app_admin_image:
    resource: "image/all.yml"
    prefix:   /image/

app_admin_video:
    resource: "video/all.yml"
    prefix:   /video/

app_admin_youtube_link:
    resource: "youtube_link/all.yml"
    prefix:   /youtube_link/