AppBundle\Entity\Avatar:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\AvatarRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        user:
            targetEntity: AppBundle\Entity\User
            cascade: [ persist ]
            mappedBy: avatars
            joinColumn:
                name: user_id
                referencedColumnName: id
        model:
            targetEntity: AppBundle\Entity\AvatarModel
            cascade: [ persist ]
            joinColumn:
                name: model_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
