AppBundle\Entity\Post:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PostRepository
    fields:
        name:
            type: string
            length: 255
            nullable: true
        description:
            type: string
            length: 255
            nullable: true
        lastUpdate:
            type: datetime
        published:
            type: boolean
    oneToOne:
        content:
            targetEntity: AppBundle\Entity\Content
            cascade: [ persist, remove ]
            joinColumn:
                nullable: false
    oneToMany:
        likeVotes:
            targetEntity: AppBundle\Entity\LikeVote
            mappedBy: post
            cascade: [ persist, remove ]
        favoriteVotes:
            targetEntity: AppBundle\Entity\FavoriteVote
            mappedBy: post
            cascade: [ persist, remove ]
    lifecycleCallbacks: {  }
