AppBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
            unique: true
        email:
            type: string
            length: 255
            unique: true
        password:
            type: string
            length: 255
        salt:
            type: string
            length: 255
        roles:
            type: array
        enabled:
            type: boolean
        token:
            type: string
            length: 255
            nullable: true
        level:
            type: integer
            length: 10
        passwordToken:
            type: string
            length: 255
            nullable: true
    oneToOne:
        setting:
            targetEntity: AppBundle\Entity\Setting
            cascade: [ persist, remove ]
    oneToMany:
        achievements:
            targetEntity: AppBundle\Entity\Achievement
            cascade: [ persist, remove ]
            mappedBy: user
            joinColumn:
                name: achievement_id
                referencedColumnName: id